version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cirrusci/flutter:latest
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
      - restore_cache:
          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
      - run: sudo gem install bundler
      - run: cd android && bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Building Android bundle
          command: flutter build appbundle