version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cirrusci/flutter:latest
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
      - restore_cache:
          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
      - run: sudo gem install bundler
      - run: cd android && bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: ls
      - run: ls ../
      - run: ls ../../
      - run: cd ../ && mkdir keys && cd keys && touch flutter-boilerplate-upload-keystore.jks
      - run: cd ../keys && ls && echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > flutter-boilerplate-upload-keystore.jks
      - run: ls
      - run: ls ../
      - run: ls ../../

#      - run: ls
#      - run: cd ../ && ls
#      - run: cd ../../ && ls
#      - run: echo "$PLAY_STORE_UPLOAD_KEY"
#      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > /home/cirrus/project/keys/flutter-boilerplate-upload-keystore.jks
      - run:
          name: Building Android bundle
          command: flutter build appbundle