version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cirrusci/flutter:latest
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: whoami 
      - run: chown -R cirrus:cirrus /var/lib/gems
      - run: gem install bundler
      - run: cd android
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle